local bluTables = {}

bluTables.BLU = {
    ["Pollen"] = { type = "Healing", mods = { ['MND'] = '???', ['VIT'] = '???' } },
    ["Sandspin"] = { type = "Magical", mods = { ['INT'] = 20 } },
    ["Foot Kick"] = { type = "Physical", mods = { ['STR'] = 10, ['DEX'] = 10 } },
    ["Sprout Smack"] = { type = "Physical", mods = { ['VIT'] = 30 } },
    ["Wild Oats"] = { type = "Physical", mods = { ['AGI'] = 30 } },
    ["Power Attack"] = { "Physical", mods = { ['STR'] = 10, ['VIT'] = 10 } },
    ["Cocoon"] = { "Enhancing", mods = { ['No BLU mods'] = '???' } },
    ["Metallic Body"] = { "Enhancing", mods = { ['No BLU mods'] = '???' } },
    ["Queasyshroom"] = { "Physical", mods = { ['INT'] = 20 } },
    ["Battle Dance"] = { "Physical", mods = { ['STR'] = 30 } },
    ["Feather Storm"] = { "Physical", mods = { ['AGI'] = 30 } },
    ["Head Butt"] = { type = "Physical", mods = { ['STR'] = 20, ['INT'] = 20 } },
    ["Healing Breeze"] = { "Healing", mods = { ['MND'] = '???' } },
    ["Sheep Song"] = { "Enfeebling", mods = { ['No BLU mods'] = '???' } },
    ["Helldive"] = { "Physical", mods = { ['AGI'] = 30 } },
    ["Cursed Sphere"] = { "Magical", mods = { ['INT'] = 30 } },
    ["Blastbomb"] = { "Magical", mods = { ['INT'] = 20 } },
    ["Bludgeon"] = { "Physical", mods = { ['CHR'] = 30 } },
    ["Blood Drain"] = { "Magical", mods = { ['No BLU mods'] = '???'} },
    ["Claw Cyclone"] = { "Physical", mods = { ['DEX'] = 30 } },
    ["Poison Breath"] = { "Breath", mods = { ['No BLU mods'] = '???' } },
    ["Soporific"] = { type = "Enfeebling", mods = { ['No Blu Mods'] = '???' } },
    ["Screwdriver"] = { "Physical", mods = { ['STR'] = 20, ['MND'] = 20 } },
    ["Bomb Toss"] = { "Magical", mods = { ['INT'] = 20 } },
    ["Grand Slam"] = { "Physical", mods = { ['VIT'] = 30 } },
    ["Wild Carrot"] = { "Healing", mods = { ['MND'] = '???' } },
    ["Chaotic Eye"] = { "Enfeelbing", mods = { ['No BLU mods'] = '???' } },
    ["Sound Blast"] = { "Enfeebling", mods = { ['No BLU mods'] = '???' } },
    ["Death Ray"] = { "Magical", mods = { ['INT'] = 20, ['MND'] = 20 } },
    ["Smite of Rage"] = { "Physical", mods = { ['STR'] = 20, ['DEX'] = 20 } },
    ["Digest"] = { "Magical", mods = { ['No BLU mods'] = '???' } },
    ["Pinecone Bomb"] = { "Physical", mods = { ['STR'] = 20, ['AGI'] = 20 } },
    ["Blank Gaze"] = { "Enfeebling", mods = { ['No BLU mods'] = '???' } },
    ["Jet Stream"] = { "Physical", mods = { ['AGI'] = 30 } },
    ["Uppercut"] = { "Physical", mods = { ['STR'] = 35 } },
    ["Mysterious Light"] = { "Magical", mods = { ['CHR'] = 30 } },
    ["Terror Touch"] = { "Physical", mods = { ['DEX'] = 20, ['INT'] = 20 } },
    ["MP Drainkiss"] = { "Magical", mods = { ['No BLU mods'] = '???' } },
    ["Venom Shell"] = { "Enfeebling", mods = { ['No BLU mods'] = '???' } },
    ["Stinking Gas"] = { "Enfeebling", mods = { ['No BLU mods'] = '???' } },
    ["Blitzstrahl"] = { "Magical", mods = { ['INT'] = 30, ['MND'] = 10 } },
    ["Mandibular Bite"] = { "Physical", mods = { ['STR'] = 20, ['INT'] = 20 } },
    ["Awful Eye"] = { "Enfeebling", mods = { ['No BLU mods'] = '???' } },
    ["Geist Wall"] = { "Enfeebling", mods = { ['No BLU mods'] = '???' } },
    ["Magnetite Cloud"] = { "Breath", mods = { ['No BLU mods'] = '???' } },
    ["Jettatura"] = { "Enfeebling", mods = { ['No BLU mods'] = '???' } },
    ["Blood Saber"] = { "Magical", mods = { ['No BLU mods'] = '???' } },
    ["Refueling"] = { "Enhancing", mods = { ['No BLU mods'] = '???' } },
    ["Sickle Slash"] = { "Physical", mods = { ['DEX'] = 50 } },
    ["Ice Break"] = { "Magical", mods = { ['INT'] = 30 } },
    ["Self-Destruct"] = { "Magical", mods = { ['No BLU mods'] = '???' } },
    ["Frightful Roar"] = { "Enfeebling", mods = { ['No BLU mods'] = '???' } },
    ["Cold Wave"] = { "Enfeebling", mods = { ['No BLU mods'] = '???' } },
    ["Filamented Hold"] = { "Enfeebling", mods = { ['AGI'] = '???' } },
    ["Hecatomb Wave"] = { "Breath", mods = { ['No BLU mods'] = '???' } },
    ["Radiant Breath"] = { "Breath", mods = { ['No BLU mods'] = '???' } },
    ["Feather Barrier"] = { "Enhancing", mods = { ['No BLU mods'] = '???' } },
    ["Light of Penance"] = { "Enfeebling", mods = { ['No BLU mods'] = '???' } },
    ["Flying Hip Press"] = { "Breath", mods = { ['No BLU mods'] = '???' } },
    ["Magic Fruit"] = { type = "Healing", mods = { ['VIT'] = '???', ['MND'] = '???' } },
    ["Dimensional Death"] = { "Physical", mods = { ['STR'] = 50 } },
    ["Spiral Spin"] = { "Physical", mods = { ['AGI'] = 30 } },
    ["Death Scissors"] = { "Physical", mods = { ['STR'] = 60 } },
    ["Eyes on Me"] = { "Magical", mods = { ['CHR'] = 40 } },
    ["Bad Breath"] = { "Breath", mods = { ['No BLU mods'] = '???' } },
    ["Maelstrom"] = { "Magical", mods = { ['INT'] = 30, ['MND'] = 10 } },
    ["Seedspray"] = { "Physical", mods = { ['DEX'] = 30 } },
    ["1000 Needles"] = { "Magical", mods = { ['No BLU mods'] = '???' } },
    ["Memento Mori"] = { "Enhancing", mods = { ['No BLU mods'] = '???' } },
    ["Body Slam"] = { "Physical", mods = { ['VIT'] = 40 } },
    ["Hydro Shot"] = { "Physical", mods = { ['AGI'] = 30 } },
    ["Frypan"] = { "Physical", mods = { ['STR'] = 20, ['MND'] = 20 } },
    ["Freneetic Rip"] = { type = "Physical", mods = { ['STR'] = 20, ['DEX'] = 20 } },
    ["Spinal Cleave"] = { "Physical", mods = { ['STR'] = 30 } },
    ["Voracious Trunk"] = { "Enfeebling", mods = { ['No BLU mods'] = '???' } },
    ["Feather Tickle"] = { "Enfeebling", mods = { ['No BLU mods'] = '???' } },
    ["Yawn"] = { "Enfeebling", mods = { ['No BLU mods'] = '???' } },
    ["Infrasonics"] = { "Enfeebling", mods = { ['No BLU mods'] = '???' } },
    ["Zephyr Mantle"] = { "Enhancing", mods = { ['No BLU mods'] = '???' } },
    ["Corrosive Ooze"] = { "Magical", mods = { ['INT'] = 20 } },
    ["Sandspray"] = { "Enfeebling", mods = { ['No BLU mods'] = '???' } },
    ["Frost Breath"] = { "Breath", mods = { ['No BLU mods'] = '???' } },
    ["Diamondhide"] = { "Enhancing", mods = { ['No BLU mods'] = '???' } },
    ["Enervation"] = { type = "Enfeebling", mods = { ['No BLU mods'] = '???' } },
    ["Firespit"] = { "Magical", mods = { ['INT'] = 20, ['MND'] = 20 } },
    ["Tail Slap"] = { "Physical", mods = { ['STR'] = 20, ['VIT'] = 50 } },
    ["Hysteric Barrage"] = { "Physical", mods = { ['DEX'] = 30 } },
    ["Asuran Claws"] = { type = "Physical", mods = { ['STR'] = '???' } },
    ["Cannonball"] = { "Physical", mods = { ['STR'] = 50, ['VIT'] = 50 } },
    ["Amplification"] = { "Enhancing", mods = { ['No BLU mods'] = '???' } },
    ["Heat Breath"] = { "Breath", mods = { ['No BLU mods'] = '???' } },
    ["Lowing"] = { "Enfeebling", mods = { ['No BLU mods'] = '???' } },
    ["Triumphant Roar"] = { "Enhancing", mods = { ['No BLU mods'] = '???'} },
    ["Saline Coat"] = { type = "Enhancing", mods = { ['No BLU mods'] = '???' } },
    ["Disseverment"] = { type = "Physical", mods = { ['STR'] = 20, ['DEX'] = 20} },
    ["Sub-zero Smash"] = { "Physical", mods = { ['MND'] = '???' } },
    ["Temporal Shift"] = { "Enhancing", mods = { ['No BLU mods'] = '???' } },
    ["Ram Charge"] = { "Physical", mods = { ['STR'] = 30, ['MND'] = 50 } },
    ["Mind Blast"] = { "Magical", mods = { ['MND'] = 30 } },
    ["Actinic Burst"] = { "Enfeebling", mods = { ['No BLU mods'] = '???' } },
    ["Reactor Cool"] = { "Enhancing", mods = { ['No BLU mods'] = '???' } },
    ["Magic Hammer"] = { "Magical", mods = { ['MND'] = 30 } },
    ["Exuviation"] = { "Healing", mods = { ['No BLU mods'] = '???' } },
    ["Plasma Charge"] = { "Enhancing", mods = { ['No BLU mods'] = '???' } },
    ["Vertical Cleave"] = { type = "Physical", mods = { ['STR'] = 50 } },
    ["Plenilune Embrace"] = { "Healing", mods = { ['MND'] = 200 } },
    ["Acrid Stream"] = { "Magical", mods = { ['INT'] = '???' } },
    ["Leafstorm"] = "Magical",
    ["Cimicine Discharge"] = "Enfeebling",
    ["Regeneration"] = "Enhancing",
    ["Animating Wail"] = "Enhancing",
    ["Battery Charge"] = "Enhancing",
    ["Blazing Bound"] = "Magical",
    ["Demoralizing Roar"] = "Enfeebling",
    ["Final Sting"] = "Physical",
    ["Goblin Rush"] = "Physical",
    ["Vanity Dive"] = "Physical",
    ["Magic Barrier"] = "Enhancing",
    ["Whirl of Rage"] = "Physical",
    ["Benthic Typhoon"] = "Physical",
    ["Auroral Drape"] = "Enhancing",
    ["Osmosis"] = "Magical",
    ["Quad. Continuum"] = "Physical",
    ["Fantod"] = "Enfeebling",
    ["Thermal Pulse"] = "Magical",
    ["Empty Thrash"] = "Physical",
    ["Dream Flower"] = "Enfeebling",
    ["Occultation"] = "Enhancing",
    ["Charged Whisker"] = "Magical",
    ["Winds of Promy."] = "Healing",
    ["Delta Thrust"] = "Physical",
    ["Everyone. Grudge"] = "Magical",
    ["Reaving Wind"] = "Enfeebling",
    ["Barrier Tusk"] = "Enhancing",
    ["Mortal Ray"] = "Enfeebling",
    ["Water Bomb"] = "Magical",
    ["Heavy Strike"] = "Physical",
    ["Dark Orb"] = "Magical",
    ["White Wind"] = "Healing",
    ["Sudden Lunge"] = "Physical",
    ["Thunderbolt"] = "Magical",
    ["Harden Shell"] = "Enhancing",
    ["Quadrastrike"] = "Physical",
    ["Vapor Spray"] = "Breath",
    ["Absolute Terror"] = "Enfeebling",
    ["Thunder Breath"] = "Breath",
    ["Gates of Hades"] = "Magical",
    ["Tourbillion"] = "Physical",
    ["O. Counterstance"] = "Enhancing",
    ["Amorphic Spikes"] = "Physical",
    ["Pyric Bulwark"] = "Enhancing",
    ["Wind Breath"] = "Breath",
    ["Barbed Crescent"] = "Physical",
    ["Bilgestorm"] = "Physical",
    ["Bloodrake"] = "Physical",

}


bluTables.GetBLU = function(name)
    local bluTable = bluTables.BLU[name];
    local BLUtype = 'Not Blue Magic';
    local BLUmods = { ['No BLU mods'] = '???'};
    if(bluTable ~= nil)then
        BLUtype = bluTable.type;
    end
    if(bluTable ~= nil)then
        BLUmods = bluTable.mods;
    end
    return BLUtype, BLUmods;
end

return bluTables;